# Generated by Django 3.1.7 on 2021-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
