# Generated by Django 3.1.7 on 2021-04-25 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0009_auto_20210425_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userseen', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feed.comments')),
                ('fromuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationfrom', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feed.post')),
                ('touser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
